/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppCart {
    }
    interface AppCartItem {
        "count": CartItemProps['count'];
        "name": CartItemProps['name'];
        "pic": CartItemProps['pic'];
        "price": CartItemProps['price'];
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppLayout {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface AppShimmer {
    }
}
declare global {
    interface HTMLAppCartElement extends Components.AppCart, HTMLStencilElement {
    }
    var HTMLAppCartElement: {
        prototype: HTMLAppCartElement;
        new (): HTMLAppCartElement;
    };
    interface HTMLAppCartItemElement extends Components.AppCartItem, HTMLStencilElement {
    }
    var HTMLAppCartItemElement: {
        prototype: HTMLAppCartItemElement;
        new (): HTMLAppCartItemElement;
    };
    interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {
    }
    var HTMLAppHeaderElement: {
        prototype: HTMLAppHeaderElement;
        new (): HTMLAppHeaderElement;
    };
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppLayoutElement extends Components.AppLayout, HTMLStencilElement {
    }
    var HTMLAppLayoutElement: {
        prototype: HTMLAppLayoutElement;
        new (): HTMLAppLayoutElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppShimmerElement extends Components.AppShimmer, HTMLStencilElement {
    }
    var HTMLAppShimmerElement: {
        prototype: HTMLAppShimmerElement;
        new (): HTMLAppShimmerElement;
    };
    interface HTMLElementTagNameMap {
        "app-cart": HTMLAppCartElement;
        "app-cart-item": HTMLAppCartItemElement;
        "app-header": HTMLAppHeaderElement;
        "app-home": HTMLAppHomeElement;
        "app-layout": HTMLAppLayoutElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "app-shimmer": HTMLAppShimmerElement;
    }
}
declare namespace LocalJSX {
    interface AppCart {
    }
    interface AppCartItem {
        "count"?: CartItemProps['count'];
        "name"?: CartItemProps['name'];
        "pic"?: CartItemProps['pic'];
        "price"?: CartItemProps['price'];
    }
    interface AppHeader {
    }
    interface AppHome {
    }
    interface AppLayout {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface AppShimmer {
    }
    interface IntrinsicElements {
        "app-cart": AppCart;
        "app-cart-item": AppCartItem;
        "app-header": AppHeader;
        "app-home": AppHome;
        "app-layout": AppLayout;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "app-shimmer": AppShimmer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-cart": LocalJSX.AppCart & JSXBase.HTMLAttributes<HTMLAppCartElement>;
            "app-cart-item": LocalJSX.AppCartItem & JSXBase.HTMLAttributes<HTMLAppCartItemElement>;
            "app-header": LocalJSX.AppHeader & JSXBase.HTMLAttributes<HTMLAppHeaderElement>;
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-layout": LocalJSX.AppLayout & JSXBase.HTMLAttributes<HTMLAppLayoutElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-shimmer": LocalJSX.AppShimmer & JSXBase.HTMLAttributes<HTMLAppShimmerElement>;
        }
    }
}
